version: "3.4"

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  db:
    image: 
    environment:
      - name=value
